version: '2'

services:
  yumrepo:
    image: intraway/yum-repo
    hostname: yumrepo
    container_name: yumrepo
    ports:
      - 80
    volumes:
      - ./extras/dummyrepo:/var/repo:rw
      - /etc/localtime:/etc/localtime
    environment:
      - REPO_PORT=80
      - REPO_PATH=/var/repo
      - REPO_DEPTH=2

  centos6:
    image: centos:6
    hostname: centos6-client
    container_name: centos6-client
    links:
      - yumrepo:repo
    volumes:
      - ./extras/yum/container.repo:/etc/yum.repos.d/container.repo:ro
      - /etc/localtime:/etc/localtime
    command: yum --disablerepo=* --enablerepo=container install dummy-package-1.2

  centos7:
    image: centos:7
    hostname: centos7-client
    container_name: centos7-client
    links:
      - yumrepo:repo
    volumes:
      - ./extras/yum/container.repo:/etc/yum.repos.d/container.repo:ro
      - /etc/localtime:/etc/localtime
    command: yum --disablerepo=* --enablerepo=container info dummy-package-1.0_SNAPSHOT
